config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'blogs#index' #追記
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
    # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # 以下のコードの意味の解説
    # ログイン中のユーザに管理者権限がある場合はrails_adminへのアクセスと、
    # すべてのモデルのCRUD（Create、Read、Update、Delete）を許可する
    if user&.admin?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { public: 0, private: 1 }, _prefix: true
  # 上記のように_prefix: trueを記述してない状態でブラウザを開いたら、エラーが出ることがある。
  # エラー文を確認すると、publicというメソッドが重複しているとのこと。
  # 重複してエラーが出ていなければ_prefix: trueを記述しなくてもOK。
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
# deviseのストロングパラメータ設定には、専用のメソッドconfigure_permitted_parametersがあります。
# deviseのコントローラはgem本体にあるため、ストロングパラメータはapplication_controllerに設定します。
class ApplicationController < ActionController::Base
  class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # deviseで作成したこのUserというモデル（の、マイグレーションファイル）に、自分でnameというカラムを追加したとします。
      # deviseはdeviseが初期で作るカラムには自動でストロングパラメータの設定をしますが、独自実装したカラムには当然その設定はないので、
      # そのままそのカラムに値を保存しようとするとストロングパラメータで弾かれてしまいます。なので、上記のような記述をすることで、
      # nameカラムがUserのストロングパラメータに加わり、無事に保存ができるようになるわけです。
      # 上記では、sign_up時に[:name]の値を許す設定になっています。
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
      # update（ユーザー情報更新）の際は上記のようにします。
    end
  end
end

# このコードは、RailsアプリケーションのApplicationControllerに定義されたクラスであり、devise gemで認証機能を実装する際に使用されます。
# before_actionメソッドは、指定したアクションが呼び出される前に、このクラス内で定義されたconfigure_permitted_parametersメソッドを実行することを指定します。
# このメソッドは、deviseのコントローラーであるかどうかを確認し、deviseのユーザー登録(sign up)フォームで許可するパラメーターを設定します。ここでは、:nameパラメーターを許可しています。
# protectedキーワードは、このクラスの下に定義されたメソッドがプライベートメソッドとして扱われるようにします。
# つまり、このクラス外部から直接呼び出すことはできませんが、他のメソッド内で呼び出すことはできます。

# if: :devise_controller?はどういう意味
# if: :devise_controller?は、before_actionメソッドのオプションとして渡され、このクラスのアクションがDeviseのコントローラーであるかどうかを確認します。
# これは、Deviseのコントローラーでないアクションが呼び出された場合、configure_permitted_parametersメソッドが実行されないようにするためです。
# :devise_controller?は、Devise gemが提供するヘルパーメソッドで、Deviseのコントローラーであるかどうかを判定します。
# 具体的には、DeviseのコントローラーはDevise::SessionsController、Devise::RegistrationsController、Devise::ConfirmationsController、Devise::UnlocksController、Devise::PasswordsControllerです。
# devise_controller?メソッドは、現在のコントローラーがこれらのクラスのいずれかを継承している場合、真を返します。
# したがって、if: :devise_controller?は、現在のコントローラーがDeviseのコントローラーである場合にconfigure_permitted_parametersメソッドを実行することを保証します。

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]
  before_action :authenticate_user!,  only: [:new, :edit, :update, :destroy]  # こうすると未ログインでも閲覧だけは可能

  def index
    @blogs = Blog.all.order(created_at: :desc).page(params[:page])
    # ページネーション導入
    # @blogs = Blog.all.includes(:user).order(created_at: :desc).page(params[:page])
    # お試し実装なのでここまでしなくてOK。
  end

  def show
    if @blog.status_private? && @blog.user != current_user
      respond_to do |format|
        format.html { redirect_to blogs_path, notice: 'このページにはアクセスできません' }
      end
    end
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "新規投稿を行いました。" }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :status)
    # params.require(:blog).permit(:title, :content, :status, {:cat_ids => []})
    # のようにするとcategoryのidも受け渡しできるようになる。今回は未使用。
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label(:public, for: nil, class:'post-status__label') do %>
      <%= form.radio_button :status, :public %>
      <%= I18n.t('activerecord.attributes.post.statuses.public') %>
    <% end %>
    <%= form.label(:private, for: nil, class:'post-status__label') do %>
      <%= form.radio_button :status, :private %>
      <%= I18n.t('activerecord.attributes.post.statuses.private') %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>








<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% if current_user&.admin? %>
<%# if current_user.try!admin?はと意味は同じ。 %>
  <h1>Blogs_admin</h1>
<% else %>
  <h1>Blogs</h1>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>
<%= paginate @blogs, theme: 'twitter-bootstrap-4'  %>   <%# 一般的にはビューの最下部に配置される %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "ブログ投稿", blogs_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>

    <div>あなたの名前:<%#= current_user.name %></div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>